CREATE OR REPLACE FUNCTION fnc_fibonacci(pstop INTEGER DEFAULT 10)
RETURNS TABLE (A INTEGER) AS
$BODY$
WITH RECURSIVE R(A, B) AS (
    SELECT 0 AS A, 1 AS B
    UNION ALL
    SELECT B, A + B
    FROM R
    WHERE B < pstop)
SELECT A
FROM R;
$BODY$ LANGUAGE sql;

